---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: taco-wagon
  name: taco-wagon-api-keys
spec:
  type: kv-v2
  mount: secret
  path: taco-wagon/api-keys
  destination:
    name: taco-wagon-api-keys
    create: true
  refreshAfter: 30s
  vaultAuthRef: taco-wagon-auth