apiVersion: v1
kind: ServiceAccount
metadata:
  # SA bound to the VSO namespace for transit engine auth
  namespace: taco-wagon
  name: taco-wagon-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: taco-wagon
  name: taco-wagon-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: taco-wagon
    # ServiceAccount to use when authenticating to Vault
    # it is recommended to always provide a unique serviceAccount per Pod/application
    serviceAccount: taco-wagon-app
